# Generated B-UML Model
from besser.BUML.metamodel.structural import (
    Class, Property, DomainModel,
    IntegerType, Enumeration, EnumerationLiteral
)

# Import referenced models
from generated_models._3gpp_5g_common_yang_types import domain_model as types5g3gpp_model
from generated_models._3gpp_common_yang_types import domain_model as types3gpp_model

# Classes
DESManagementFunction = Class(name="DESManagementFunction")

# DESManagementFunction class attributes and methods
DESManagementFunction_desSwitch: Property = Property(name="desSwitch", type=BooleanType)
DESManagementFunction_energySavingState: Property = Property(name="energySavingState", type=enumeration)
DESManagementFunction_isProbingCapable: Property = Property(name="isProbingCapable", type=enumeration)
DESManagementFunction_intraRatEsActivationOriginalCellLoadParameters: Property = Property(name="intraRatEsActivationOriginalCellLoadParameters", type=list)
DESManagementFunction_intraRatEsActivationCandidateCellsLoadParameters: Property = Property(name="intraRatEsActivationCandidateCellsLoadParameters", type=list)
DESManagementFunction_intraRatEsDeactivationCandidateCellsLoadParameters: Property = Property(name="intraRatEsDeactivationCandidateCellsLoadParameters", type=list)
DESManagementFunction_esNotAllowedTimePeriod: Property = Property(name="esNotAllowedTimePeriod", type=list)
DESManagementFunction_interRatEsActivationOriginalCellParameters: Property = Property(name="interRatEsActivationOriginalCellParameters", type=list)
DESManagementFunction_interRatEsActivationCandidateCellParameters: Property = Property(name="interRatEsActivationCandidateCellParameters", type=list)
DESManagementFunction_interRatEsDeactivationCandidateCellParameters: Property = Property(name="interRatEsDeactivationCandidateCellParameters", type=list)
DESManagementFunction.attributes={DESManagementFunction_desSwitch, DESManagementFunction_energySavingState, DESManagementFunction_isProbingCapable, DESManagementFunction_intraRatEsActivationOriginalCellLoadParameters, DESManagementFunction_intraRatEsActivationCandidateCellsLoadParameters, DESManagementFunction_intraRatEsDeactivationCandidateCellsLoadParameters, DESManagementFunction_esNotAllowedTimePeriod, DESManagementFunction_interRatEsActivationOriginalCellParameters, DESManagementFunction_interRatEsActivationCandidateCellParameters, DESManagementFunction_interRatEsDeactivationCandidateCellParameters}

IntraRatEsActivationOriginalCellLoadParameters = Class(name="IntraRatEsActivationOriginalCellLoadParameters")

# IntraRatEsActivationOriginalCellLoadParameters class attributes and methods
IntraRatEsActivationOriginalCellLoadParameters_loadThreshold: Property = Property(name="loadThreshold", type=IntegerType)
IntraRatEsActivationOriginalCellLoadParameters_timeDuration: Property = Property(name="timeDuration", type=IntegerType)
IntraRatEsActivationOriginalCellLoadParameters.attributes={IntraRatEsActivationOriginalCellLoadParameters_loadThreshold, IntraRatEsActivationOriginalCellLoadParameters_timeDuration}

IntraRatEsActivationCandidateCellsLoadParameters = Class(name="IntraRatEsActivationCandidateCellsLoadParameters")

# IntraRatEsActivationCandidateCellsLoadParameters class attributes and methods
IntraRatEsActivationCandidateCellsLoadParameters_loadThreshold: Property = Property(name="loadThreshold", type=IntegerType)
IntraRatEsActivationCandidateCellsLoadParameters_timeDuration: Property = Property(name="timeDuration", type=IntegerType)
IntraRatEsActivationCandidateCellsLoadParameters.attributes={IntraRatEsActivationCandidateCellsLoadParameters_loadThreshold, IntraRatEsActivationCandidateCellsLoadParameters_timeDuration}

IntraRatEsDeactivationCandidateCellsLoadParameters = Class(name="IntraRatEsDeactivationCandidateCellsLoadParameters")

# IntraRatEsDeactivationCandidateCellsLoadParameters class attributes and methods
IntraRatEsDeactivationCandidateCellsLoadParameters_loadThreshold: Property = Property(name="loadThreshold", type=IntegerType)
IntraRatEsDeactivationCandidateCellsLoadParameters_timeDuration: Property = Property(name="timeDuration", type=IntegerType)
IntraRatEsDeactivationCandidateCellsLoadParameters.attributes={IntraRatEsDeactivationCandidateCellsLoadParameters_loadThreshold, IntraRatEsDeactivationCandidateCellsLoadParameters_timeDuration}

EsNotAllowedTimePeriod = Class(name="EsNotAllowedTimePeriod")

# EsNotAllowedTimePeriod class attributes and methods
EsNotAllowedTimePeriod_startTimeandendTime: Property = Property(name="startTimeandendTime", type=StringType)
EsNotAllowedTimePeriod_periodOfDay: Property = Property(name="periodOfDay", type=StringType)
EsNotAllowedTimePeriod_daysOfWeekList: Property = Property(name="daysOfWeekList", type=StringType)
EsNotAllowedTimePeriod_listoftimeperiods: Property = Property(name="listoftimeperiods", type=StringType)
EsNotAllowedTimePeriod.attributes={EsNotAllowedTimePeriod_startTimeandendTime, EsNotAllowedTimePeriod_periodOfDay, EsNotAllowedTimePeriod_daysOfWeekList, EsNotAllowedTimePeriod_listoftimeperiods}

InterRatEsActivationOriginalCellParameters = Class(name="InterRatEsActivationOriginalCellParameters")

# InterRatEsActivationOriginalCellParameters class attributes and methods
InterRatEsActivationOriginalCellParameters_loadThreshold: Property = Property(name="loadThreshold", type=IntegerType)
InterRatEsActivationOriginalCellParameters_timeDuration: Property = Property(name="timeDuration", type=IntegerType)
InterRatEsActivationOriginalCellParameters.attributes={InterRatEsActivationOriginalCellParameters_loadThreshold, InterRatEsActivationOriginalCellParameters_timeDuration}

InterRatEsActivationCandidateCellParameters = Class(name="InterRatEsActivationCandidateCellParameters")

# InterRatEsActivationCandidateCellParameters class attributes and methods
InterRatEsActivationCandidateCellParameters_loadThreshold: Property = Property(name="loadThreshold", type=IntegerType)
InterRatEsActivationCandidateCellParameters_timeDuration: Property = Property(name="timeDuration", type=IntegerType)
InterRatEsActivationCandidateCellParameters.attributes={InterRatEsActivationCandidateCellParameters_loadThreshold, InterRatEsActivationCandidateCellParameters_timeDuration}

InterRatEsDeactivationCandidateCellParameters = Class(name="InterRatEsDeactivationCandidateCellParameters")

# InterRatEsDeactivationCandidateCellParameters class attributes and methods
InterRatEsDeactivationCandidateCellParameters_loadThreshold: Property = Property(name="loadThreshold", type=IntegerType)
InterRatEsDeactivationCandidateCellParameters_timeDuration: Property = Property(name="timeDuration", type=IntegerType)
InterRatEsDeactivationCandidateCellParameters.attributes={InterRatEsDeactivationCandidateCellParameters_loadThreshold, InterRatEsDeactivationCandidateCellParameters_timeDuration}

